// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBetdjHjBrjwwhfrdP1zLh4shnYdiMYCck',
    appId: '1:374108513424:web:d5a2e524fc5516b4536415',
    messagingSenderId: '374108513424',
    projectId: 'meethub026',
    authDomain: 'meethub026.firebaseapp.com',
    storageBucket: 'meethub026.appspot.com',
    measurementId: 'G-6VGTL6811K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcMDr60uV4BGx50TtUS_64WNFIgSja6ac',
    appId: '1:374108513424:android:7d9bc59868119e5f536415',
    messagingSenderId: '374108513424',
    projectId: 'meethub026',
    storageBucket: 'meethub026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhLLuNc9NIyvtxt3hWWY-rakOvlyKmTcQ',
    appId: '1:374108513424:ios:bed84e86bfb0a9c2536415',
    messagingSenderId: '374108513424',
    projectId: 'meethub026',
    storageBucket: 'meethub026.appspot.com',
    iosBundleId: 'com.example.meethub026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBetdjHjBrjwwhfrdP1zLh4shnYdiMYCck',
    appId: '1:374108513424:web:8405f46774e218c5536415',
    messagingSenderId: '374108513424',
    projectId: 'meethub026',
    authDomain: 'meethub026.firebaseapp.com',
    storageBucket: 'meethub026.appspot.com',
    measurementId: 'G-QWVQPYYFM2',
  );

}